#!/usr/bin/env python3
"""
Auto-generated Mininet topology.
Source: N01 network  (25 nodes, 24 edges, cycle-free MST)
Generated by gml_to_mininet.py
"""

from mininet.net import Mininet
from mininet.node import OVSSwitch, Controller, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.clean import cleanup
import time

NODES = [{'id': 0, 'label': 'N01', 'lon': 200.0, 'lat': 175.0}, {'id': 1, 'label': 'N02', 'lon': 203.0, 'lat': 92.0}, {'id': 2, 'label': 'N03', 'lon': 269.0, 'lat': 20.0}, {'id': 3, 'label': 'N04', 'lon': 287.0, 'lat': 158.0}, {'id': 4, 'label': 'N05', 'lon': 290.0, 'lat': 115.0}, {'id': 5, 'label': 'N06', 'lon': 367.0, 'lat': 150.0}, {'id': 6, 'label': 'N07', 'lon': 308.0, 'lat': 70.0}, {'id': 7, 'label': 'N08', 'lon': 397.0, 'lat': 131.0}, {'id': 8, 'label': 'N09', 'lon': 482.0, 'lat': 137.0}, {'id': 9, 'label': 'N10', 'lon': 58.0, 'lat': 113.0}, {'id': 10, 'label': 'N11', 'lon': 41.0, 'lat': 249.0}, {'id': 11, 'label': 'N12', 'lon': 92.0, 'lat': 204.0}, {'id': 12, 'label': 'N13', 'lon': 381.0, 'lat': 250.0}, {'id': 13, 'label': 'N14', 'lon': 378.0, 'lat': 297.0}, {'id': 14, 'label': 'N15', 'lon': 257.0, 'lat': 303.0}, {'id': 15, 'label': 'N16', 'lon': 184.0, 'lat': 248.0}, {'id': 16, 'label': 'N17', 'lon': 130.0, 'lat': 118.0}, {'id': 17, 'label': 'N18', 'lon': 59.0, 'lat': 293.0}, {'id': 18, 'label': 'N19', 'lon': 31.0, 'lat': 353.0}, {'id': 19, 'label': 'N20', 'lon': 176.0, 'lat': 394.0}, {'id': 20, 'label': 'N21', 'lon': 135.0, 'lat': 333.0}, {'id': 21, 'label': 'N22', 'lon': 413.0, 'lat': 329.0}, {'id': 22, 'label': 'N23', 'lon': 358.0, 'lat': 394.0}, {'id': 23, 'label': 'N24', 'lon': 268.0, 'lat': 398.0}, {'id': 24, 'label': 'N25', 'lon': 235.0, 'lat': 188.0}]

# Cycle-free MST edges (24 of original)
EDGES = [{'source': 10, 'target': 14, 'dist': 2202.46}, {'source': 12, 'target': 14, 'dist': 2985.5}, {'source': 9, 'target': 16, 'dist': 3292.97}, {'source': 5, 'target': 7, 'dist': 3293.54}, {'source': 2, 'target': 8, 'dist': 3997.48}, {'source': 0, 'target': 24, 'dist': 4143.59}, {'source': 10, 'target': 15, 'dist': 4524.45}, {'source': 3, 'target': 4, 'dist': 4787.75}, {'source': 6, 'target': 7, 'dist': 5021.64}, {'source': 12, 'target': 13, 'dist': 5225.78}, {'source': 2, 'target': 9, 'dist': 5670.62}, {'source': 10, 'target': 11, 'dist': 6022.23}, {'source': 2, 'target': 6, 'dist': 6136.2}, {'source': 14, 'target': 17, 'dist': 6148.27}, {'source': 4, 'target': 5, 'dist': 6409.21}, {'source': 3, 'target': 24, 'dist': 6576.45}, {'source': 17, 'target': 18, 'dist': 7002.86}, {'source': 22, 'target': 23, 'dist': 7770.56}, {'source': 19, 'target': 23, 'dist': 7924.64}, {'source': 19, 'target': 20, 'dist': 8044.43}, {'source': 14, 'target': 20, 'dist': 9220.73}, {'source': 0, 'target': 1, 'dist': 9232.09}, {'source': 21, 'target': 22, 'dist': 9246.41}, {'source': 9, 'target': 11, 'dist': 10511.01}]


def build_topology() -> None:
    setLogLevel("info")

    net = Mininet(switch=OVSSwitch,
                 controller=RemoteController)
    info("*** Adding remote controller\n")
    net.addController("c0", controller=RemoteController,
                      ip="127.0.0.1", port=6653)

    # --------------------------------------------------------------
    # Switches
    # --------------------------------------------------------------
    info("*** Adding switches\n")
    switches = {}
    for node in NODES:
        nid   = node["id"]
        label = node.get("label", f"node{nid}")
        sw    = net.addSwitch(f"s{nid}", cls=OVSSwitch,
                              protocols="OpenFlow13")
        switches[nid] = sw
        info(f"    s{nid}  ({label})\n")

    # --------------------------------------------------------------
    # Hosts  (one per switch)
    # --------------------------------------------------------------
    info("*** Adding hosts\n")
    h1   = net.addHost("h1", ip="10.0.1.1/24", mac="00:00:00:00:00:01")  # N01
    h2   = net.addHost("h2", ip="10.0.1.2/24", mac="00:00:00:00:00:02")  # N02
    h3   = net.addHost("h3", ip="10.0.1.3/24", mac="00:00:00:00:00:03")  # N03
    h4   = net.addHost("h4", ip="10.0.1.4/24", mac="00:00:00:00:00:04")  # N04
    h5   = net.addHost("h5", ip="10.0.1.5/24", mac="00:00:00:00:00:05")  # N05
    h6   = net.addHost("h6", ip="10.0.1.6/24", mac="00:00:00:00:00:06")  # N06
    h7   = net.addHost("h7", ip="10.0.1.7/24", mac="00:00:00:00:00:07")  # N07
    h8   = net.addHost("h8", ip="10.0.1.8/24", mac="00:00:00:00:00:08")  # N08
    h9   = net.addHost("h9", ip="10.0.1.9/24", mac="00:00:00:00:00:09")  # N09
    h10  = net.addHost("h10", ip="10.0.1.10/24", mac="00:00:00:00:00:0a")  # N10
    h11  = net.addHost("h11", ip="10.0.1.11/24", mac="00:00:00:00:00:0b")  # N11
    h12  = net.addHost("h12", ip="10.0.1.12/24", mac="00:00:00:00:00:0c")  # N12
    h13  = net.addHost("h13", ip="10.0.1.13/24", mac="00:00:00:00:00:0d")  # N13
    h14  = net.addHost("h14", ip="10.0.1.14/24", mac="00:00:00:00:00:0e")  # N14
    h15  = net.addHost("h15", ip="10.0.1.15/24", mac="00:00:00:00:00:0f")  # N15
    h16  = net.addHost("h16", ip="10.0.1.16/24", mac="00:00:00:00:00:10")  # N16
    h17  = net.addHost("h17", ip="10.0.1.17/24", mac="00:00:00:00:00:11")  # N17
    h18  = net.addHost("h18", ip="10.0.1.18/24", mac="00:00:00:00:00:12")  # N18
    h19  = net.addHost("h19", ip="10.0.1.19/24", mac="00:00:00:00:00:13")  # N19
    h20  = net.addHost("h20", ip="10.0.1.20/24", mac="00:00:00:00:00:14")  # N20
    h21  = net.addHost("h21", ip="10.0.1.21/24", mac="00:00:00:00:00:15")  # N21
    h22  = net.addHost("h22", ip="10.0.1.22/24", mac="00:00:00:00:00:16")  # N22
    h23  = net.addHost("h23", ip="10.0.1.23/24", mac="00:00:00:00:00:17")  # N23
    h24  = net.addHost("h24", ip="10.0.1.24/24", mac="00:00:00:00:00:18")  # N24
    h25  = net.addHost("h25", ip="10.0.1.25/24", mac="00:00:00:00:00:19")  # N25

    # --------------------------------------------------------------
    # Host <-> switch links
    # --------------------------------------------------------------
    info("*** Linking hosts to switches\n")
    net.addLink(h1, switches[0])
    net.addLink(h2, switches[1])
    net.addLink(h3, switches[2])
    net.addLink(h4, switches[3])
    net.addLink(h5, switches[4])
    net.addLink(h6, switches[5])
    net.addLink(h7, switches[6])
    net.addLink(h8, switches[7])
    net.addLink(h9, switches[8])
    net.addLink(h10, switches[9])
    net.addLink(h11, switches[10])
    net.addLink(h12, switches[11])
    net.addLink(h13, switches[12])
    net.addLink(h14, switches[13])
    net.addLink(h15, switches[14])
    net.addLink(h16, switches[15])
    net.addLink(h17, switches[16])
    net.addLink(h18, switches[17])
    net.addLink(h19, switches[18])
    net.addLink(h20, switches[19])
    net.addLink(h21, switches[20])
    net.addLink(h22, switches[21])
    net.addLink(h23, switches[22])
    net.addLink(h24, switches[23])
    net.addLink(h25, switches[24])

    # --------------------------------------------------------------
    # Inter-switch links (MST — no cycles)
    # --------------------------------------------------------------
    info("*** Adding inter-switch links\n")
    for e in EDGES:
        src, dst = e["source"], e["target"]
        info(f"    s{src} <--> s{dst}\n")
        net.addLink(switches[src], switches[dst])

    info("*** Starting network\n")
    net.start()
    tcpreplay_cmd = "tcpreplay --multiplier=1 --limit=100000 "
    start_ts = time.time()

    # BLOCKING call → guarantees same timing
    folder = "univ2/"
    for h, pcap in [(h1,"h1"), (h2,"h2"), (h3,"h3"),
                (h4,"h4"), (h5,"h5"), (h6,"h6")]:
        h.sendCmd(tcpreplay_cmd + f"--intf1={h.name}-eth0 {folder}{pcap}.pcap")

    # Now wait for all of them to finish
    for h in [h1, h2, h3, h4, h5, h6]:
        h.waitOutput()
    info("*** Stopping network\n")
    net.stop()
    cleanup()


if __name__ == "__main__":
    build_topology()
