#!/usr/bin/env python3
"""
Auto-generated Mininet topology.
Source: Hannover network  (17 nodes, 16 edges, cycle-free MST)
Generated by gml_to_mininet.py
"""

from mininet.net import Mininet
from mininet.node import OVSSwitch, Controller, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.clean import cleanup
import time

NODES = [{'id': 0, 'label': 'Hannover', 'lon': 9.8, 'lat': 52.39}, {'id': 1, 'label': 'Frankfurt', 'lon': 8.66, 'lat': 50.14}, {'id': 2, 'label': 'Hamburg', 'lon': 10.08, 'lat': 53.55}, {'id': 3, 'label': 'Norden', 'lon': 7.21, 'lat': 53.6}, {'id': 4, 'label': 'Bremen', 'lon': 8.8, 'lat': 53.08}, {'id': 5, 'label': 'Berlin', 'lon': 13.48, 'lat': 52.52}, {'id': 6, 'label': 'Muenchen', 'lon': 11.55, 'lat': 48.15}, {'id': 7, 'label': 'Ulm', 'lon': 9.99, 'lat': 48.4}, {'id': 8, 'label': 'Nuernberg', 'lon': 11.08, 'lat': 49.45}, {'id': 9, 'label': 'Stuttgart', 'lon': 9.12, 'lat': 48.73}, {'id': 10, 'label': 'Karlsruhe', 'lon': 8.41, 'lat': 49.01}, {'id': 11, 'label': 'Mannheim', 'lon': 8.49, 'lat': 49.49}, {'id': 12, 'label': 'Essen', 'lon': 7.0, 'lat': 51.44}, {'id': 13, 'label': 'Dortmund', 'lon': 7.48, 'lat': 51.51}, {'id': 14, 'label': 'Duesseldorf', 'lon': 6.78, 'lat': 51.22}, {'id': 15, 'label': 'Koeln', 'lon': 7.01, 'lat': 50.92}, {'id': 16, 'label': 'Leipzig', 'lon': 12.38, 'lat': 51.34}]

# Cycle-free MST edges (16 of original)
EDGES = [{'source': 12, 'target': 14, 'dist': 28.85}, {'source': 12, 'target': 13, 'dist': 34.15}, {'source': 14, 'target': 15, 'dist': 37.04}, {'source': 10, 'target': 11, 'dist': 53.7}, {'source': 9, 'target': 10, 'dist': 60.56}, {'source': 1, 'target': 11, 'dist': 73.32}, {'source': 7, 'target': 9, 'dist': 73.81}, {'source': 2, 'target': 4, 'dist': 99.83}, {'source': 0, 'target': 4, 'dist': 102.1}, {'source': 6, 'target': 7, 'dist': 118.78}, {'source': 3, 'target': 4, 'dist': 120.39}, {'source': 1, 'target': 15, 'dist': 145.38}, {'source': 6, 'target': 8, 'dist': 148.64}, {'source': 5, 'target': 16, 'dist': 151.38}, {'source': 0, 'target': 13, 'dist': 186.74}, {'source': 0, 'target': 16, 'dist': 212.21}]


def build_topology() -> None:
    setLogLevel("info")

    net = Mininet(switch=OVSSwitch,
                 controller=RemoteController)
    info("*** Adding remote controller\n")
    net.addController("c0", controller=RemoteController,
                      ip="127.0.0.1", port=6653)

    # --------------------------------------------------------------
    # Switches
    # --------------------------------------------------------------
    info("*** Adding switches\n")
    switches = {}
    for node in NODES:
        nid   = node["id"]
        label = node.get("label", f"node{nid}")
        sw    = net.addSwitch(f"s{nid}", cls=OVSSwitch,
                              protocols="OpenFlow13")
        switches[nid] = sw
        info(f"    s{nid}  ({label})\n")

    # --------------------------------------------------------------
    # Hosts  (one per switch)
    # --------------------------------------------------------------
    info("*** Adding hosts\n")
    h1   = net.addHost("h1", ip="10.0.1.1/24", mac="00:00:00:00:00:01")  # Hannover
    h2   = net.addHost("h2", ip="10.0.1.2/24", mac="00:00:00:00:00:02")  # Frankfurt
    h3   = net.addHost("h3", ip="10.0.1.3/24", mac="00:00:00:00:00:03")  # Hamburg
    h4   = net.addHost("h4", ip="10.0.1.4/24", mac="00:00:00:00:00:04")  # Norden
    h5   = net.addHost("h5", ip="10.0.1.5/24", mac="00:00:00:00:00:05")  # Bremen
    h6   = net.addHost("h6", ip="10.0.1.6/24", mac="00:00:00:00:00:06")  # Berlin
    h7   = net.addHost("h7", ip="10.0.1.7/24", mac="00:00:00:00:00:07")  # Muenchen
    h8   = net.addHost("h8", ip="10.0.1.8/24", mac="00:00:00:00:00:08")  # Ulm
    h9   = net.addHost("h9", ip="10.0.1.9/24", mac="00:00:00:00:00:09")  # Nuernberg
    h10  = net.addHost("h10", ip="10.0.1.10/24", mac="00:00:00:00:00:0a")  # Stuttgart
    h11  = net.addHost("h11", ip="10.0.1.11/24", mac="00:00:00:00:00:0b")  # Karlsruhe
    h12  = net.addHost("h12", ip="10.0.1.12/24", mac="00:00:00:00:00:0c")  # Mannheim
    h13  = net.addHost("h13", ip="10.0.1.13/24", mac="00:00:00:00:00:0d")  # Essen
    h14  = net.addHost("h14", ip="10.0.1.14/24", mac="00:00:00:00:00:0e")  # Dortmund
    h15  = net.addHost("h15", ip="10.0.1.15/24", mac="00:00:00:00:00:0f")  # Duesseldorf
    h16  = net.addHost("h16", ip="10.0.1.16/24", mac="00:00:00:00:00:10")  # Koeln
    h17  = net.addHost("h17", ip="10.0.1.17/24", mac="00:00:00:00:00:11")  # Leipzig

    # --------------------------------------------------------------
    # Host <-> switch links
    # --------------------------------------------------------------
    info("*** Linking hosts to switches\n")
    net.addLink(h1, switches[0])
    net.addLink(h2, switches[1])
    net.addLink(h3, switches[2])
    net.addLink(h4, switches[3])
    net.addLink(h5, switches[4])
    net.addLink(h6, switches[5])
    net.addLink(h7, switches[6])
    net.addLink(h8, switches[7])
    net.addLink(h9, switches[8])
    net.addLink(h10, switches[9])
    net.addLink(h11, switches[10])
    net.addLink(h12, switches[11])
    net.addLink(h13, switches[12])
    net.addLink(h14, switches[13])
    net.addLink(h15, switches[14])
    net.addLink(h16, switches[15])
    net.addLink(h17, switches[16])

    # --------------------------------------------------------------
    # Inter-switch links (MST — no cycles)
    # --------------------------------------------------------------
    info("*** Adding inter-switch links\n")
    for e in EDGES:
        src, dst = e["source"], e["target"]
        info(f"    s{src} <--> s{dst}\n")
        net.addLink(switches[src], switches[dst])

    info("*** Starting network\n")
    net.start()
    
    tcpreplay_cmd = "tcpreplay --multiplier=1 --limit=100000 "
    start_ts = time.time()

    # BLOCKING call → guarantees same timing
    folder = "univ2/"
    h1.cmd(tcpreplay_cmd + "--intf1=h1-eth0 " + folder + "h1.pcap &")
    h2.cmd(tcpreplay_cmd + "--intf1=h2-eth0 " + folder + "h2.pcap &")
    h3.cmd(tcpreplay_cmd + "--intf1=h3-eth0 " + folder + "h3.pcap &")
    h4.cmd(tcpreplay_cmd + "--intf1=h4-eth0 " + folder + "h4.pcap &")
    h5.cmd(tcpreplay_cmd + "--intf1=h5-eth0 " + folder + "h5.pcap &")
    h6.cmd(tcpreplay_cmd + "--intf1=h6-eth0 " + folder + "h6.pcap &")
    time.sleep(50)
    end_ts = time.time()

    print(f"*** tcpreplay finished in {end_ts - start_ts:.2f}s")
    for h in [h1, h2, h3, h4, h5, h6]:
        h.cmd("pkill -f tcpreplay")
    info("*** Stopping network\n")
    net.stop()
    cleanup()


if __name__ == "__main__":
    build_topology()
