#!/usr/bin/env python3
"""
Auto-generated Mininet topology.
Source: Gdansk network  (12 nodes, 11 edges, cycle-free MST)
Generated by gml_to_mininet.py
"""
import time
from mininet.net import Mininet
from mininet.node import OVSSwitch, Controller, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.clean import cleanup


NODES = [{'id': 0, 'label': 'Gdansk', 'lon': 18.6, 'lat': 54.2}, {'id': 1, 'label': 'Bydgoszcz', 'lon': 17.9, 'lat': 53.1}, {'id': 2, 'label': 'Kolobrzeg', 'lon': 16.1, 'lat': 54.2}, {'id': 3, 'label': 'Katowice', 'lon': 18.8, 'lat': 50.3}, {'id': 4, 'label': 'Krakow', 'lon': 19.8, 'lat': 50.0}, {'id': 5, 'label': 'Bialystok', 'lon': 23.1, 'lat': 53.1}, {'id': 6, 'label': 'Lodz', 'lon': 19.4, 'lat': 51.7}, {'id': 7, 'label': 'Poznan', 'lon': 16.8, 'lat': 52.4}, {'id': 8, 'label': 'Rzeszow', 'lon': 21.9, 'lat': 50.0}, {'id': 9, 'label': 'Szczecin', 'lon': 14.5, 'lat': 53.4}, {'id': 10, 'label': 'Warsaw', 'lon': 21.0, 'lat': 52.2}, {'id': 11, 'label': 'Wroclaw', 'lon': 16.9, 'lat': 51.1}]

# Cycle-free MST edges (11 of original)
EDGES = [{'source': 3, 'target': 4, 'dist': 78.7}, {'source': 1, 'target': 7, 'dist': 107.45}, {'source': 6, 'target': 10, 'dist': 122.98}, {'source': 2, 'target': 9, 'dist': 137.71}, {'source': 7, 'target': 11, 'dist': 144.76}, {'source': 4, 'target': 8, 'dist': 150.13}, {'source': 3, 'target': 11, 'dist': 160.72}, {'source': 3, 'target': 6, 'dist': 161.28}, {'source': 0, 'target': 2, 'dist': 162.65}, {'source': 1, 'target': 2, 'dist': 170.43}, {'source': 5, 'target': 10, 'dist': 173.49}]


def build_topology() -> None:
    setLogLevel("info")

    net = Mininet(switch=OVSSwitch,
                 controller=RemoteController)
    info("*** Adding remote controller\n")
    net.addController("c0", controller=RemoteController,
                      ip="127.0.0.1", port=6653)

    # --------------------------------------------------------------
    # Switches
    # --------------------------------------------------------------
    info("*** Adding switches\n")
    switches = {}
    for node in NODES:
        nid   = node["id"]
        label = node.get("label", f"node{nid}")
        sw    = net.addSwitch(f"s{nid}", cls=OVSSwitch,
                              protocols="OpenFlow13")
        switches[nid] = sw
        info(f"    s{nid}  ({label})\n")

    # --------------------------------------------------------------
    # Hosts  (one per switch)
    # --------------------------------------------------------------
    info("*** Adding hosts\n")
    h1   = net.addHost("h1", ip="10.0.1.1/24", mac="00:00:00:00:00:01")  # Gdansk
    h2   = net.addHost("h2", ip="10.0.1.2/24", mac="00:00:00:00:00:02")  # Bydgoszcz
    h3   = net.addHost("h3", ip="10.0.1.3/24", mac="00:00:00:00:00:03")  # Kolobrzeg
    h4   = net.addHost("h4", ip="10.0.1.4/24", mac="00:00:00:00:00:04")  # Katowice
    h5   = net.addHost("h5", ip="10.0.1.5/24", mac="00:00:00:00:00:05")  # Krakow
    h6   = net.addHost("h6", ip="10.0.1.6/24", mac="00:00:00:00:00:06")  # Bialystok
    h7   = net.addHost("h7", ip="10.0.1.7/24", mac="00:00:00:00:00:07")  # Lodz
    h8   = net.addHost("h8", ip="10.0.1.8/24", mac="00:00:00:00:00:08")  # Poznan
    h9   = net.addHost("h9", ip="10.0.1.9/24", mac="00:00:00:00:00:09")  # Rzeszow
    h10  = net.addHost("h10", ip="10.0.1.10/24", mac="00:00:00:00:00:0a")  # Szczecin
    h11  = net.addHost("h11", ip="10.0.1.11/24", mac="00:00:00:00:00:0b")  # Warsaw
    h12  = net.addHost("h12", ip="10.0.1.12/24", mac="00:00:00:00:00:0c")  # Wroclaw

    # --------------------------------------------------------------
    # Host <-> switch links
    # --------------------------------------------------------------
    info("*** Linking hosts to switches\n")
    net.addLink(h1, switches[0])
    net.addLink(h2, switches[1])
    net.addLink(h3, switches[2])
    net.addLink(h4, switches[3])
    net.addLink(h5, switches[4])
    net.addLink(h6, switches[5])
    net.addLink(h7, switches[6])
    net.addLink(h8, switches[7])
    net.addLink(h9, switches[8])
    net.addLink(h10, switches[9])
    net.addLink(h11, switches[10])
    net.addLink(h12, switches[11])

    # --------------------------------------------------------------
    # Inter-switch links (MST — no cycles)
    # --------------------------------------------------------------
    info("*** Adding inter-switch links\n")
    for e in EDGES:
        src, dst = e["source"], e["target"]
        info(f"    s{src} <--> s{dst}\n")
        net.addLink(switches[src], switches[dst])

    info("*** Starting network\n")
    net.start()
    
    info("*** Run pingall twice: first pass seeds MACs, second confirms\n")
    print("\n=== Network is running ===")
    tcpreplay_cmd = "tcpreplay --multiplier=1 --limit=100000 "
    start_ts = time.time()

    # BLOCKING call → guarantees same timing
    folder = "univ2/"
    h1.cmd(tcpreplay_cmd + "--intf1=h1-eth0 " + folder + "h1.pcap &")
    h2.cmd(tcpreplay_cmd + "--intf1=h2-eth0 " + folder + "h2.pcap &")
    h3.cmd(tcpreplay_cmd + "--intf1=h3-eth0 " + folder + "h3.pcap &")
    h4.cmd(tcpreplay_cmd + "--intf1=h4-eth0 " + folder + "h4.pcap &")
    h5.cmd(tcpreplay_cmd + "--intf1=h5-eth0 " + folder + "h5.pcap &")
    h6.cmd(tcpreplay_cmd + "--intf1=h6-eth0 " + folder + "h6.pcap &")
    time.sleep(50)
    end_ts = time.time()

    print(f"*** tcpreplay finished in {end_ts - start_ts:.2f}s")
    for h in [h1, h2, h3, h4, h5, h6]:
        h.cmd("pkill -f tcpreplay")
    info("*** Stopping network\n")
    net.stop()
    cleanup()


if __name__ == "__main__":
    build_topology()
