#!/usr/bin/env python3
"""
gml_to_mininet.py  –  Convert any GML network file to a Mininet topology.

Usage:
    sudo python3 gml_to_mininet.py polska.gml
    sudo python3 gml_to_mininet.py polska.gml --remote          # remote controller
    sudo python3 gml_to_mininet.py polska.gml --bw-scale 10     # 10 Mbps per km
    sudo python3 gml_to_mininet.py polska.gml --out topo.py     # write script, don't run
"""

import argparse
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# GML parser
# ---------------------------------------------------------------------------

def parse_gml(path: str) -> tuple[list[dict], list[dict]]:
    """
    Minimal GML parser.  Returns (nodes, edges) where each element is a dict
    of the key/value pairs found inside the corresponding block.
    """
    text = Path(path).read_text()

    def parse_block(content: str) -> dict:
        result = {}
        content = re.sub(r'\w+\s*\[[^\[\]]*\]', '', content, flags=re.S)
        for key, val in re.findall(r'(\w+)\s+(".*?"|[\w.\-]+)', content):
            val = val.strip('"')
            try:
                val = int(val)
            except ValueError:
                try:
                    val = float(val)
                except ValueError:
                    pass
            result[key] = val
        return result

    nodes, edges = [], []
    for block_type, block_body in re.findall(
            r'(node|edge)\s*\[([^\[\]]*)\]', text, flags=re.S):
        data = parse_block(block_body)
        if block_type == "node":
            nodes.append(data)
        else:
            edges.append(data)

    if not nodes:
        sys.exit(f"[ERROR] No nodes found in {path}. Check the GML format.")

    return nodes, edges


# ---------------------------------------------------------------------------
# Kruskal's MST — removes all cycles
# ---------------------------------------------------------------------------

def _mst_edges(nodes: list[dict], edges: list[dict]) -> list[dict]:
    """
    Return the subset of edges forming a Minimum Spanning Tree (Kruskal's).
    Edges are sorted by 'dist' (falls back to 'weight', 'len', then 1.0).
    Any edge that would form a cycle is silently dropped.
    """
    # Union-Find
    parent = {n["id"]: n["id"] for n in nodes}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]   # path compression
            x = parent[x]
        return x

    def union(a, b):
        a, b = find(a), find(b)
        if a == b:
            return False   # cycle detected
        parent[a] = b
        return True

    def edge_weight(e):
        return e.get("dist", e.get("weight", e.get("len", 1.0)))

    kept = []
    for e in sorted(edges, key=edge_weight):
        if union(e["source"], e["target"]):
            kept.append(e)
            if len(kept) == len(nodes) - 1:
                break   # MST complete

    dropped = len(edges) - len(kept)
    if dropped:
        print(f"[MST] Removed {dropped} edge(s) that formed cycles. "
              f"Keeping {len(kept)} edge(s).")

    return kept


# ---------------------------------------------------------------------------
# Script generator
# ---------------------------------------------------------------------------

def generate_script(nodes: list[dict], edges: list[dict],
                    bw_scale: float = 1.0) -> str:
    """Return a Mininet topology script matching the hand-written style."""

    # Remove cycles before generating anything
    edges = _mst_edges(nodes, edges)

    I = "    "   # 4-space indent

    name_w = max(len(f"h{n['id']}") for n in nodes) + 1
    host_lines = []
    link_lines = []
    for n in nodes:
        nid   = n["id"]
        label = n.get("label", f"node{nid}")
        subnet = f"10.0.1.{nid+1}/24"
        mac    = ":".join(f"{nid:012x}"[i:i+2] for i in range(0, 12, 2))
        var    = f"h{nid}".ljust(name_w)
        host_lines.append(
            f'{I}{var} = net.addHost("h{nid}", ip="{subnet}", mac="{mac}")  # {label}'
        )
        link_lines.append(f'{I}net.addLink(h{nid}, switches[{nid}])')

    host_block = "\n".join(host_lines)
    link_block = "\n".join(link_lines)

    nodes_repr = repr(nodes)
    edges_repr = repr(edges)

    sep = f"{I}# " + "-" * 62

    lines = [
        "#!/usr/bin/env python3",
        '"""',
        "Auto-generated Mininet topology.",
        f"Source: {nodes[0].get('label', 'unknown')} network  "
        f"({len(nodes)} nodes, {len(edges)} edges, cycle-free MST)",
        "Generated by gml_to_mininet.py",
        '"""',
        "",
        "from mininet.net import Mininet",
        "from mininet.node import OVSSwitch, Controller, RemoteController",
        "from mininet.cli import CLI",
        "from mininet.log import setLogLevel, info",
        "from mininet.clean import cleanup",
        "",
        "",
        f"NODES = {nodes_repr}",
        "",
        f"# Cycle-free MST edges ({len(edges)} of original)",
        f"EDGES = {edges_repr}",
        "",
        "",
        "def build_topology() -> None:",
        f'{I}setLogLevel("info")',
        "",
        f'{I}net = Mininet(switch=OVSSwitch,',
        f'{I}             controller=RemoteController)',
        f'{I}info("*** Adding remote controller\\n")',
        f'{I}net.addController("c0", controller=RemoteController,',
        f'{I}                  ip="127.0.0.1", port=6653)',
        "",
        sep,
        f"{I}# Switches",
        sep,
        f'{I}info("*** Adding switches\\n")',
        f"{I}switches = {{}}",
        f"{I}for node in NODES:",
        f'{I}{I}nid   = node["id"]',
        f'{I}{I}label = node.get("label", f"node{{nid}}")',
        f'{I}{I}sw    = net.addSwitch(f"s{{nid}}", cls=OVSSwitch,',
        f'{I}{I}                      protocols="OpenFlow13")',
        f"{I}{I}switches[nid] = sw",
        f'{I}{I}info(f"    s{{nid}}  ({{label}})\\n")',
        "",
        sep,
        f"{I}# Hosts  (one per switch)",
        sep,
        f'{I}info("*** Adding hosts\\n")',
        host_block,
        "",
        sep,
        f"{I}# Host <-> switch links",
        sep,
        f'{I}info("*** Linking hosts to switches\\n")',
        link_block,
        "",
        sep,
        f"{I}# Inter-switch links (MST — no cycles)",
        sep,
        f'{I}info("*** Adding inter-switch links\\n")',
        f"{I}for e in EDGES:",
        f'{I}{I}src, dst = e["source"], e["target"]',
        f'{I}{I}info(f"    s{{src}} <--> s{{dst}}\\n")',
        f"{I}{I}net.addLink(switches[src], switches[dst])",
        "",
        f'{I}info("*** Starting network\\n")',
        f"{I}net.start()",
        f"{I}import time",
        f"{I}time.sleep(20)",
        f'{I}info("*** Run pingall twice: first pass seeds MACs, second confirms\\n")',
        f"{I}CLI(net)",
        f'{I}info("*** Stopping network\\n")',
        f"{I}net.stop()",
        f"{I}cleanup()",
        "",
        "",
        'if __name__ == "__main__":',
        f"{I}build_topology()",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert a GML network file to a Mininet topology script."
    )
    parser.add_argument("gml", help="Path to the input .gml file")
    parser.add_argument(
        "--out", metavar="FILE",
        help="Write the generated script to FILE instead of running it directly."
    )
    parser.add_argument(
        "--bw-scale", type=float, default=1.0, metavar="FACTOR",
        help="Link bandwidth = dist_km × FACTOR Mbps (default 1.0)"
    )
    args = parser.parse_args()

    print(f"[*] Parsing {args.gml} …")
    nodes, edges = parse_gml(args.gml)
    print(f"[*] Found {len(nodes)} nodes and {len(edges)} edges.")

    # Always apply MST when running directly too
    edges = _mst_edges(nodes, edges)

    if args.out:
        script = generate_script(nodes, edges, bw_scale=args.bw_scale)
        Path(args.out).write_text(script)
        print(f"[*] Topology script written to: {args.out}")
        print(f"    Run it with:  sudo python3 {args.out}")
    else:
        try:
            from mininet.net import Mininet
            from mininet.node import OVSSwitch, RemoteController
            from mininet.cli import CLI
            from mininet.log import setLogLevel, info
            from mininet.link import TCLink
        except ImportError:
            sys.exit("[ERROR] Mininet is not installed. "
                     "Use --out to generate a script instead.")

        bw_scale = args.bw_scale
        setLogLevel("info")

        net = Mininet(switch=OVSSwitch, controller=RemoteController,
                      link=TCLink, autoSetMacs=True)
        net.addController("c0", controller=RemoteController,
                           ip="127.0.0.1", port=6653)

        switches = {}
        for node in nodes:
            nid = node["id"]
            sw = net.addSwitch(f"s{nid}", cls=OVSSwitch,
                               protocols="OpenFlow13")
            switches[nid] = sw

        for node in nodes:
            nid    = node["id"]
            subnet = f"10.0.{nid}.1/24"
            mac    = ":".join(f"{nid:012x}"[i:i+2] for i in range(0, 12, 2))
            host   = net.addHost(f"h{nid}", ip=subnet, mac=mac)
            net.addLink(host, switches[nid], bw=1000)

        for e in edges:
            src, dst = e["source"], e["target"]
            dist  = e.get("dist", e.get("weight", e.get("len", 100.0)))
            bw    = round(dist * bw_scale, 2)
            delay = f"{dist / 200:.3f}ms"
            net.addLink(switches[src], switches[dst],
                        bw=bw, delay=delay, use_htb=True)

        net.start()
        CLI(net)
        net.stop()


if __name__ == "__main__":
    main()
